OPAMPREFIX := /home/shyuan/.opam/4.11.1
DXDIR := $(OPAMPREFIX)/lib/coq/user-contrib/dx
CLIGHTGEN32DIR := $(OPAMPREFIX)/variants/compcert32/bin
COMPCERTSRCDIR := $(OPAMPREFIX)/.opam-switch/build/coq-compcert-32.3.9
